//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by resource.rc
//
#define IDS_VIEWPORT                    9
#define IDS_ADD                         20
#define IDS_REMOVE_BLOB                 21
#define IDS_REMOVE                      22
#define IDS_DISPLAY_PROPERTIES          23
#define IDS_RENDERING                   24
#define IDS_LIBDESCRIPTION              31
#define IDS_CATEGORY                    32
#define IDS_CLASS_NAME                  33
#define IDS_PARAMS                      34
#define IDS_SPIN                        35
#define IDS_SIZE                        36
#define IDS_TENSION                     37
#define IDS_RENDER                      38
#define ID_SPECULAR_PANEL               39
#define IDS_COARSENESS                  40
#define IDS_NODELIST                    41
#define IDS_USESOFTSEL                  42
#define IDS_MINSIZE                     43
#define IDS_OLDMETHOD                   44
#define IDS_PFPARAM                     45
#define IDS_USEALLPFEVENTS              46
#define IDS_PFEVENTLIST                 47
#define IDS_ADDEVENTS                   48
#define IDS_OFFINVIEW                   49
#define IDS_SPECULAR_HEAD               50
#define IDS_ANIMA_TITLE                 51
#define ID_DETAIL_PANEL                 52
#define ID_UPDATE_PANEL                 53
#define ID_INFO_PANEL                   54
#define ID_DISPLAY_PANEL                55
#define ID_RENDERING_PANEL              56
#define ID_MAIN_PANEL                   57
#define IDD_PANEL                       101
#define IDD_PFPANEL                     102
#define IDB_ANIMA_LOGO                  103
#define IDB_BITMAP1                     104
#define IDD_ADD_DIALOG                  209
#define ID_SCENE_INFO_PANEL             210
#define IDC_SPEC_HEAD_EDIT              500
#define IDC_SPEC_BODY_EDIT              501
#define IDC_SPEC_HEAD_SLIDER            600
#define IDC_SPEC_BODY_SLIDER            601
#define IDC_DETAIL_EDIT                 700
#define IDC_DETAIL_SLIDER               701
#define IDC_UPDATE_MODE_1               800
#define IDC_UPDATE_MODE_2               801
#define IDC_ADDPF_EVENT_BUTTON          1001
#define IDC_USEALLPF                    1002
#define IDC_PFLIST                      1003
#define IDC_PFREMOVE                    1004
#define IDC_COMBO1                      1006
#define IDC_COMBO_PRESET                1006
#define IDC_COMBO2                      1007
#define IDC_FILE                        1008
#define IDC_FILE_NAME                   1009
#define IDC_TENSION                     1010
#define IDC_MODEL_EDIT                  1010
#define IDC_TENSIONSPIN                 1011
#define IDC_MODEL_SLIDER                1011
#define IDC_SIZE2                       1012
#define IDC_STATIC_SCENE_INFO           1012
#define IDC_SIZE2SPIN                   1013
#define IDC_RADIO_B_NONE                1013
#define IDC_MINSIZE                     1014
#define IDC_RADIO_B_OBJ                 1014
#define IDC_EMBEDDED                    1014
#define IDC_RENDER                      1015
#define IDC_RENDERSPIN                  1016
#define IDC_RADIO_B_IMG                 1016
#define IDC_MINSIZESPIN                 1017
#define IDC_VIEWPORT                    1018
#define IDC_VIEWPORTSPIN                1019
#define IDC_AUTOCOARSE                  1020
#define IDC_OLDMETHOD                   1021
#define IDC_USESOFTSEL                  1022
#define IDC_OFFINVIEW                   1023
#define IDC_ADD                         1032
#define IDC_REMOVE                      1033
#define IDC_PICK                        1034
#define IDC_LIST1                       1036
#define IDC_EVENTLIST                   1065
#define IDC_CLOSEBUTTON                 1100
#define IDC_DOSTUFF                     1101
#define IDC_BUTTON1                     1102
#define IDC_BUTTON_FILE_BROWSE          1102
#define IDC_BUTTON_UPDATE               1103
#define IDC_BUTTON_RELOAD               1103
#define IDC_BUTTON_RELOAD2              1104
#define IDC_BUTTON_REBUILD              1104
#define IDC_HIDE                        1121
#define IDC_COLOR                       1456
#define IDC_EDIT                        1490
#define IDC_SPIN                        1496
#define IDC_SLIDER_SPECULAR_HEAD        1504
#define IDC_RENDERABLE                  1505
#define IDC_DIS_BOX                     1506
#define IDC_SMOOTING                    1506
#define IDS_PARAM_SPEC                  30551
#define IDS_PARAM_DETAIL                30552
#define IDS_SPEC_HEAD                   30553
#define IDS_SPEC_BODY                   30554
#define IDS_DETAIL                      30555
#define IDS_PARAM_UPDATE                30556
#define IDS_UPDATE_MODE                 30557
#define IDS_PARAM_INFO                  30558
#define IDS_DS_FILENAME                 30559
#define IDS_CM_FILE_TYPES               30560
#define IDS_ANIMAFILENAME               30561
#define IDS_MAX_MODEL                   30562
#define IDS_SCENE_PARAM_INFO            30566
#define IDS_RENDERABLE                  30567
#define IDS_SMOOTHING                   30568
#define IDS_BLURMODE                    30569
#define IDS_EMBEDDED                    30570

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        110
#define _APS_NEXT_COMMAND_VALUE         40001
#define _APS_NEXT_CONTROL_VALUE         1015
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
