#ifndef _Oanima_H_
#define _Oanima_H_

enum
{
	ANIMAOBJECT_PATH		= 1000,
	ANIMAOBJECT_GROUP_TEXTURES,
	ANIMAOBJECT_GROUP_DISPLAY,
	ANIMAOBJECT_GROUP_RENDERING,
	ANIMAOBJECT_GROUP_UPDATE,
	ANIMAOBJECT_GROUP_PLUGIN_INFO,
	ANIMAOBJECT_GROUP_SCENE_INFO,
	
	ANIMAOBJECT_DARKNESS,
	ANIMAOBJECT_BBOX_MODE,
	ANIMAOBJECT_RELOAD,
	ANIMAOBJECT_EMBEDDED,
	ANIMAOBJECT_EMBEDDED_FILE,
	ANIMAOBJECT_INFO_ANIMA1,
	ANIMAOBJECT_INFO_ANIMA2,
	ANIMAOBJECT_INFO_ANIMA3,
	ANIMAOBJECT_INFO_BMP,
	ANIMAOBJECT_SCENEINFO_PRESET,
	ANIMAOBJECT_SCENEINFO_ACTORS,
	ANIMAOBJECT_SCENEINFO_POLYS,
	ANIMAOBJECT_SCENEINFO_POINTS,
	ANIMAOBJECT_SCENEINFO_RENDERER,
	
	ANIMAOBJECT_GROUP_MATERIAL,
	ANIMAOBJECT_MATERIAL_OVERRIDE,

	ANIMAOBJECT_SCALE_FACTOR
};

#endif